In [1]:
import pandas as pd

In [2]:
data = pd.data.read_csv("Ecommerce Customers.csv")

In [3]:
data

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...,...,...
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,33.237660,13.566160,36.417985,3.746573,573.847438
496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145
498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,33.322501,12.391423,36.840086,2.336485,456.469510
499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642

In [4]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [5]:
data.head()

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092

In [6]:
data.isna().sum()

Email                   0
Address                 0
Avatar                  0
Avg. Session Length     0
Time on App             0
Time on Website         0
Length of Membership    0
Yearly Amount Spent     0
dtype: int64

In [7]:
data.drop(["Email","Address"],inplace=True,axis=1)

## Encoded

In [8]:
encoded = pd.get_dummies(data.Avatar) 
encoded.head()

,AliceBlue,AntiqueWhite,Aqua,Aquamarine,Azure,Beige,Bisque,Black,BlanchedAlmond,Blue,...,Teal,Thistle,Tomato,Turquoise,Violet,Wheat,White,WhiteSmoke,Yellow,YellowGreen
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
merged_data = pd.concat([data, encoded], axis='columns')

In [10]:
merged_data

,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent,AliceBlue,AntiqueWhite,Aqua,Aquamarine,...,Teal,Thistle,Tomato,Turquoise,Violet,Wheat,White,WhiteSmoke,Yellow,YellowGreen
0,Violet,34.497268,12.655651,39.577668,4.082621,587.951054,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Bisque,33.000915,11.330278,37.110597,4.104543,487.547505,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Tan,33.237660,13.566160,36.417985,3.746573,573.847438,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,Teal,33.322501,12.391423,36.840086,2.336485,456.469510,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
499,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## THE BOSTON HOUSING DATASET

In [11]:
data1 = pd.read_csv("Boston.csv")

In [12]:
data1

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [13]:

data1.rename(columns={'medv': 'price'}, inplace=True)

In [14]:
x=data1[["crim","zn","indus","chas","nox","rm","age","dis","rad","tax","ptratio","black","lstat"]]
#or data1.iloc(:,:,-1).values
y=data1.price.values

In [15]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [16]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
       17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
       25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
       23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
       32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
       34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
       20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
       26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
       31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
       22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
       42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
       36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
       32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
       20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
       20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
       22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
       21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
       19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
       32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
       18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
       16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
       13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
        7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
       12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
       27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
        8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
        9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
       10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
       15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
       19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
       29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
       20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
       23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9])

In [17]:
x.shape

(506, 13)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [19]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [20]:
x_train#data shuffle

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
245,0.19133,22.0,5.86,0,0.431,5.605,70.2,7.9549,7,330,19.1,389.13,18.46
59,0.10328,25.0,5.13,0,0.453,5.927,47.2,6.9320,8,284,19.7,396.90,9.22
276,0.10469,40.0,6.41,1,0.447,7.267,49.0,4.7872,4,254,17.6,389.25,6.05
395,8.71675,0.0,18.10,0,0.693,6.471,98.8,1.7257,24,666,20.2,391.98,17.12
416,10.83420,0.0,18.10,0,0.679,6.782,90.8,1.8195,24,666,20.2,21.57,25.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,0.28392,0.0,7.38,0,0.493,5.708,74.3,4.7211,5,287,19.6,391.13,11.74
192,0.08664,45.0,3.44,0,0.437,7.178,26.3,6.4798,5,398,15.2,390.49,2.87
117,0.15098,0.0,10.01,0,0.547,6.021,82.6,2.7474,6,432,17.8,394.51,10.30
47,0.22927,0.0,6.91,0,0.448,6.030,85.5,5.6894,3,233,17.9,392.74,18.80
172,0.13914,0.0,4.05,0,0.510,5.572,88.5,2.5961,5,296,16.6,396.90,14.69

In [21]:
y_train #arry form bcx we only took values

array([18.5, 19.6, 33.2, 13.1,  7.5, 13.6, 17.4,  8.4, 35.4, 24. , 13.4,
       26.2,  7.2, 13.1, 24.5, 37.2, 25. , 24.1, 16.6, 32.9, 36.2, 11. ,
        7.2, 22.8, 28.7, 14.4, 24.4, 18.1, 22.5, 20.5, 15.2, 17.4, 13.6,
        8.7, 18.2, 35.4, 31.7, 33. , 22.2, 20.4, 23.9, 25. , 12.7, 29.1,
       12. , 17.7, 27. , 20.6, 10.2, 17.5, 19.7, 29.8, 20.5, 14.9, 10.9,
       19.5, 22.7, 19.5, 24.6, 25. , 24.5, 50. , 14.3, 11.8, 31. , 28.7,
       16.2, 43.5, 25. , 22. , 19.9, 22.1, 46. , 22.9, 20.2, 43.1, 34.6,
       13.8, 24.3, 21.5, 24.4, 21.2, 23.8, 26.6, 25.1,  9.6, 19.4, 19.4,
        9.5, 14. , 26.5, 13.8, 34.7, 16.3, 21.7, 17.5, 15.6, 20.9, 21.7,
       12.7, 18.5, 23.7, 19.3, 12.7, 21.6, 23.2, 29.6, 21.2, 23.8, 17.1,
       22. , 36.5, 18.8, 21.9, 23.1, 20.2, 17.4, 37. , 24.1, 36.2, 15.7,
       32.2, 13.5, 17.9, 13.3, 11.7, 41.7, 18.4, 13.1, 25. , 21.2, 16. ,
       34.9, 25.2, 24.8, 21.5, 23.4, 18.9, 10.8, 21. , 27.5, 17.5, 13.5,
       28.7, 14.8, 19.1, 28.6, 13.1, 19. , 11.3, 13.3, 22.4, 20.1, 18.2,
       22.9, 20.6, 25. , 12.8, 34.9, 23.7, 50. , 29. , 30.1, 22. , 15.6,
       23.3, 30.1, 14.3, 22.8, 50. , 20.8,  6.3, 34.9, 32.4, 19.9, 20.3,
       17.8, 23.1, 20.4, 23.2,  7. , 16.8, 46.7, 50. , 22.9, 23.9, 21.4,
       21.7, 15.4, 15.3, 23.1, 23.9, 19.4, 11.9, 17.8, 31.5, 33.8, 20.8,
       19.8, 22.4,  5. , 24.5, 19.4, 15.1, 18.2, 19.3, 27.1, 20.7, 37.6,
       11.7, 33.4, 30.1, 21.4, 45.4, 20.1, 20.8, 26.4, 10.4, 21.8, 32. ,
       21.7, 18.4, 37.9, 17.8, 28. , 28.2, 36. , 18.9, 15. , 22.5, 30.7,
       20. , 19.1, 23.3, 26.6, 21.1, 19.7, 20. , 12.1,  7.2, 14.2, 17.3,
       27.5, 22.2, 10.9, 19.2, 32. , 14.5, 24.7, 12.6, 24. , 24.1, 50. ,
       16.1, 43.8, 26.6, 36.1, 21.8, 29.9, 50. , 44. , 20.6, 19.6, 28.4,
       19.1, 22.3, 20.9, 28.4, 14.4, 32.7, 13.8,  8.5, 22.5, 35.1, 31.6,
       17.8, 15.6, 20.7, 39.8, 17.8, 19.6, 14.9, 22. , 48.8, 25. , 48.5,
       23.9, 20.3, 15.2, 10.5, 19. , 16.4,  8.8, 22. , 24.8, 50. , 19.3,
       22.7, 37.3, 31.6,  8.3, 23.1, 50. , 13.9, 16.1, 25.3, 19.5, 10.2,
       19.9, 35.2, 13.4, 24.7, 11.5, 23.4, 16.7, 15.4, 18. , 28.5, 18.4,
       32.5, 50. , 50. , 19.6, 17.6, 42.3, 14.5, 13.2, 16.2, 29.6, 16.7,
       13. , 22.3, 13.4,  5. , 19.5, 14.6, 22. ,  8.1, 24.6, 33.2, 20.6,
       14.1, 14.1, 21.1, 30.3, 23.7, 21.4, 18.3,  8.5, 22.8, 22.8, 22.2,
       13.9, 25. , 18.5,  7. , 22.6, 20.1, 30.8, 31.1, 23.8, 12.5, 23.6,
       23.2, 24.2, 22.2, 27.9, 22.2, 33.1, 19.3, 18.9, 22.6, 50. , 24.8,
       18.5, 36.4, 19.2, 16.6, 23.1])

In [22]:
regressor.fit(x_train, y_train)

LinearRegression()

In [31]:
predictionss = regressor.predict(x_train)

In [32]:
predictions = regressor.predict(x_test)

In [33]:
pd.DataFrame({"original":y_test, 'pred':predictions})

     original       pred
0        22.6  24.952333
1        50.0  23.616997
2        23.0  29.205886
3         8.3  11.960705
4        21.2  21.333620
..        ...        ...
122      19.4  17.538048
123      21.2  21.502223
124      20.3  23.632813
125      18.8  20.282598
126      33.4  35.179734

[127 rows x 2 columns]

## dont test your data until you are not satisfied with traning

In [34]:
from sklearn.metrics import r2_score
r2_score(y_train,predictionss)

0.7697699488741149

In [35]:
from sklearn.metrics import r2_score
r2_score(y_test,predictions)

0.6354638433202127

In [36]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,predictions)

29.78224509230239

In [37]:
x_train.shape

(379, 13)

In [38]:
y_train.shape

(379,)

## overfitting
--training=98%
--testing=78%
## underfitting
--training=78%
--testing=68%
## bestfitting
--training=100%
--testing=95%

>>>> to resolve overfitting and under fitting (normalize data) we will follow some steps x=x/x.max()

In [40]:
x.max()

crim        88.9762
zn         100.0000
indus       27.7400
chas         1.0000
nox          0.8710
rm           8.7800
age        100.0000
dis         12.1265
rad         24.0000
tax        711.0000
ptratio     22.0000
black      396.9000
lstat       37.9700
dtype: float64

In [41]:
x=x/x.max()
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.000071,0.18,0.083273,0.0,0.617681,0.748861,0.652,0.337278,0.041667,0.416315,0.695455,1.000000,0.131156
1,0.000307,0.00,0.254867,0.0,0.538462,0.731321,0.789,0.409607,0.083333,0.340366,0.809091,1.000000,0.240716
2,0.000307,0.00,0.254867,0.0,0.538462,0.818337,0.611,0.409607,0.083333,0.340366,0.809091,0.989746,0.106136
3,0.000364,0.00,0.078587,0.0,0.525832,0.797039,0.458,0.499913,0.125000,0.312236,0.850000,0.994281,0.077430
4,0.000776,0.00,0.078587,0.0,0.525832,0.814009,0.542,0.499913,0.125000,0.312236,0.850000,1.000000,0.140374
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000704,0.00,0.430065,0.0,0.657865,0.750911,0.691,0.204395,0.041667,0.383966,0.954545,0.987629,0.254675
502,0.000509,0.00,0.430065,0.0,0.657865,0.697039,0.767,0.188636,0.041667,0.383966,0.954545,1.000000,0.239136
503,0.000683,0.00,0.430065,0.0,0.657865,0.794533,0.910,0.178741,0.041667,0.383966,0.954545,1.000000,0.148538
504,0.001232,0.00,0.430065,0.0,0.657865,0.773804,0.893,0.196998,0.041667,0.383966,0.954545,0.991308,0.170661
505,0.000533,0.00,0.430065,0.0,0.657865,0.686788,0.808,0.206572,0.041667,0.383966,0.954545,1.000000,0.207532

In [42]:
#or we will use this way nto normalize
from sklearn.preprocessing import Normalizer

In [43]:
N=Normalizer().fit_transform(x)
N

array([[3.97292701e-05, 1.00679226e-01, 4.65771473e-02, ...,
        3.88987918e-01, 5.59329033e-01, 7.33594570e-02],
       [1.63704603e-04, 0.00000000e+00, 1.35933344e-01, ...,
        4.31529376e-01, 5.33350914e-01, 1.28386288e-01],
       [1.67976998e-04, 0.00000000e+00, 1.39583180e-01, ...,
        4.43116023e-01, 5.42055407e-01, 5.81278931e-02],
       ...,
       [3.33550239e-04, 0.00000000e+00, 2.10063855e-01, ...,
        4.66244754e-01, 4.88446886e-01, 7.25530797e-02],
       [6.06442609e-04, 0.00000000e+00, 2.11751561e-01, ...,
        4.69990683e-01, 4.88091321e-01, 8.40285837e-02],
       [2.70217514e-04, 0.00000000e+00, 2.18097847e-01, ...,
        4.84076507e-01, 5.07127769e-01, 1.05245373e-01]])

#which method will use
#standarization VS normalization

>>>>>One of the most popular methods for preparing data is Normalization, 
which enables us to alter the values of numerical columns in the dataset to a standard scale.


<<<< Normalization /Standardization >>>>>

This method scales the model using minimum and maximum values/This method scales the model using the mean and standard deviation.



When features are on various scales, it is functional./When a variable's mean and standard deviation are both set to 0, it is beneficial. 

Values on the scale fall between [0, 1] and [-1, 1]./Values on a scale are not constrained to a particular range.

Additionally known as scaling normalization. /This process is called Z-score normalization.

When the feature distribution is unclear, it is helpful./When the feature distribution is consistent, it is helpful.

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(N,y,random_state=0)

In [46]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [47]:
regressor.fit(x_train, y_train)

LinearRegression()

In [48]:
predictions = regressor.predict(x_test)

In [49]:
from sklearn.metrics import r2_score
r2_score(y_test,predictions)

0.6341929455838604

In [50]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,predictions)

29.886076186084782

## Regularization Techniques 
---There are two main types of regularization techniques: Ridge Regularization and Lasso Regularization.

Ridge Regularization : 


Also known as Ridge Regression, it modifies the over-fitted or under fitted models by adding the penalty equivalent to the sum of the squares of the magnitude of coefficients.

Lasso Regression 


It modifies the over-fitted or under-fitted models by adding the penalty equivalent to the sum of the absolute values of coefficients. 
coeeficient of X is slope here  y = m*X+c
lambda= the penalty term is represented by Lambda Î»

In [51]:
from sklearn.linear_model import Lasso

In [52]:
lasso=Lasso(alpha=0.1) # alpha == penalty term

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [54]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.1)

In [55]:


predictions = lasso.predict(x_test)

In [56]:
from sklearn.metrics import r2_score
r2_score(y_test,predictions)

0.560433057562385

In [57]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,predictions)

35.912186416258734

In [58]:
#changing value of alpha

In [59]:
from sklearn.linear_model import Lasso

In [60]:
lasso=Lasso(alpha=0.001)

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [62]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.001)

In [63]:
predictions = lasso.predict(x_test)

In [64]:
from sklearn.metrics import r2_score
r2_score(y_test,predictions)

0.6350205384975464

In [65]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,predictions) #error reduced

29.818462659853154

In [66]:
from sklearn.linear_model import Ridge

In [67]:
ridge=Ridge(alpha=0.01)

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [69]:
ridge.fit(x_train, y_train)

Ridge(alpha=0.01)

In [70]:
predictions = ridge.predict(x_test)

In [71]:
from sklearn.metrics import r2_score
r2_score(y_test,predictions)

0.6353144622900371

In [72]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,predictions)

29.794449375392855